FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY src ./src
COPY configs ./configs
RUN mkdir -p data
CMD ["python", "-m", "src.train_models", "--config", "configs/train_config.yaml"]
